version: '3'

services:

    laravel:
      image: laravel:latest
      build:
        context: .
        dockerfile: ./docker/development/Dockerfile
      container_name: laravel
      expose:
        - "80"
        - "443"
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - mysql

    mysql:
      image: mysql:8.0
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=laravel
      expose:
        - "33061"
      ports:
        - "33061:3306"
      volumes:
        - ./storage/mysql-data:/var/lib/mysql
        - ./docker/development/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql