version: '3'

services:

    laravel:
      image: laravel:latest
      build:
        context: ./
        dockerfile: ./docker/development/Dockerfile
      container_name: laravel
      ports:
        - "8084:80"
      links:
        - mysql

    mysql:
      image: mysql:5.7
      container_name: mysql
      #command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=laravel
      ports:
        - "33071:3306"
      volumes:
        - ./storage/mysql-data:/var/lib/mysql
        - ./docker/development/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql